# Generated by Django 3.0.2 on 2020-01-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('activite', models.CharField(choices=[(1, 'HAREKETSİZ'), (2, 'HAFTADA 1 - 3 GÜN EKSERSİZ'), (3, 'HAFTADA 3 - 5 GÜN EKSERSİZ'), (4, 'HAFTADA 6 - 7 GÜN EKSERSİZ'), (5, 'HAFTADA 1 - 3 GÜN EKSERSİZ')], default=1, max_length=1)),
                ('kilo', models.DecimalField(decimal_places=2, max_digits=3)),
                ('boy', models.DecimalField(decimal_places=2, max_digits=3)),
                ('date_of_birth', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
