# Generated by Django 3.0.2 on 2020-01-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='boy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='kilo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
    ]
